version: '2'

services:
  ca.org.thefact.io:
    image: hyperledger/fabric-ca:$ARCH-1.1.0
    environment:
      - TZ=Asia/Seoul
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org.thefact.io
      # - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/org.thefact.io-cert.pem
      # - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e488df9bb67b7f6dc3d6a4becc86d838923f1e3f0d660f98690773911889c89e_sk

    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org.thefact.io-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e488df9bb67b7f6dc3d6a4becc86d838923f1e3f0d660f98690773911889c89e_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org.thefact.io/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org.thefact.io

  orderer.thefact.io:
    container_name: orderer.thefact.io
    image: hyperledger/fabric-orderer:$ARCH-1.1.0
    environment:
      - TZ=Asia/Seoul
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/thefact.io/orderers/orderer.thefact.io/msp:/etc/hyperledger/msp/orderer/msp

  peer0.org.thefact.io:
    container_name: peer0.org.thefact.io
    image: hyperledger/fabric-peer:$ARCH-1.1.0
    environment:
      - TZ=Asia/Seoul
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org.thefact.io
      - CORE_PEER_ADDRESS=peer0.org.thefact.io:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=OrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    # command: peer node start --peer-defaultchain=false
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org.thefact.io/peers/peer0.org.thefact.io/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org.thefact.io/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.thefact.io
      - couchdb0

  couchdb0:
      container_name: couchdb0
      image: hyperledger/fabric-couchdb:$ARCH-0.4.6
      ports:
        - 5984:5984
      environment:
        DB_URL: http://localhost:5984/member_db

  peer1.org.thefact.io:
    container_name: peer1.org.thefact.io
    image: hyperledger/fabric-peer:$ARCH-1.1.0
    environment:
      - TZ=Asia/Seoul
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org.thefact.io
      - CORE_PEER_ADDRESS=peer1.org.thefact.io:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=OrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    # command: peer node start --peer-defaultchain=false
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org.thefact.io/peers/peer1.org.thefact.io/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org.thefact.io/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.thefact.io
      - couchdb1

  couchdb1:
      container_name: couchdb1
      image: hyperledger/fabric-couchdb:$ARCH-0.4.6
      ports:
        - 6984:5984
      environment:
        DB_URL: http://localhost:5984/member_db
